services:
  php-laravel-api:
    container_name: php-laravel-api
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./api/:/var/www/html/
    ports:
      - '8000:8000'
    environment:
      - XDEBUG_MODE=coverage
    platform: linux/amd64
    networks:
      - tasks
    depends_on:
      - mysql

  react:
    container_name: react-js
    image: node:20
    user: "root"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./app/:/home/node/app
    command: >
      bash -c "npm install && npm run dev"
    tty: true
    restart: none
    ports:
    - '3000:5173'

  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'tasks-mysql:/var/lib/mysql'
    networks:
      - tasks
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s

networks:
  tasks:
    driver: bridge

volumes:
  tasks-mysql:
    driver: local
